In [1]:
import pandas as pd
from bs4 import BeautifulSoup as Soup
import requests as Re
import numpy as np
import csv

In [2]:
Jumia=[]
for x in range(1,51):
    url=f"https://www.jumia.com.ng/catalog/?q=laptops&page={x}#catalog-listing"
    html=Re.get(url).text
    html_data=Soup(html, "html.parser")
    data=html_data.find_all("div",{"info"})
    
    for Laptop_data in data:
        Name=Laptop_data.find("h3",{"class":"name"}).text
        Price=Laptop_data.find("div", {"class":"prc"}).text
        Price=Price[1:].replace(",","")
        try:
            Old_Price=(Laptop_data.find("div", {"class":"old"}).text)[1:].replace(",","")
        except:
            Old_Price=None
        try:
            Discount=Laptop_data.find("div", {"class":"bdg _dsct _sm"}).text

        except:
            Discount=None
        try:
            Rating=(Laptop_data.find("div", {"class":"stars _s"}).text)[:3].replace("o","")
        except:
            Rating=None
        
        Jumia.append([Name, Price, Old_Price, Discount, Rating])

In [3]:
df=pd.DataFrame(Jumia, columns=["Name", "Price", "Old Price", "%Discount", "Rating"])
df

,Name,Price,Old Price,%Discount,Rating
0,Hp PROBOOK 450G6 8TH GEN INTEL CORE I5 8GB RAM...,750000,None,None,5
1,Ace Elec ACE 14.1'' Intel Celeron J4105 4Core ...,225000,799000,72%,4
2,Hp Stream 11 Intel Celeron 2GB RAM- 32GB HDD W...,140000,None,None,4.8
3,Ace Elec ACE 14.1'' Intel Celeron J4105 4Core ...,275000,890000,69%,None
4,DELL Refurbished Dell Latitude E5470 14-Inch L...,248660,600000,59%,1
...,...,...,...,...,...
1995,Hp ENVY 17 INTEL CORE I7 13TH GEN 1TB SSD 32GB...,2184800,None,None,None
1996,DELL Latitude 7490 TOUCHSCREEN Core I7/16GB RA...,750000,980000,23%,None
1997,Hp PAVILION 14 12TH GEN INTEL CORE I7 8GB RAM ...,1130500,None,None,None
1998,Hp VICTUS GAMING 16 12TH GEN INTEL CORE I7 8GB...,1873000,None,None,None
1999,"Acer TRAVELMATE P2 11th Gen, INTEL CORE I7 8GB...",740100,790000,6%,3

In [4]:
df.to_csv("Jumia Laptop Data.csv")